/** Vertical offset applied to all hooks (drops them below the top edge). */
export const HOOK_TOP_OFFSET = 40;

/** Global size multiplier for side bills (applied to each hook's scale). */
export const BILL_SIZE_MULTIPLIER = 2.5;

export type SideHookConfig = {
  id: string;
  left: string;
  drop: number;
  topExtra: number;
  scale: number;
  zIndex: number;
  swayDelay: number;
  swayDuration: number;
  swayAngle: number;
  scrollGrowSpeed: number;
};

type HookDef = {
  offsetVw: number;
  drop: number;
  topExtra: number;
  zIndex: number;
  swayDelay: number;
  swayDuration: number;
  swayAngle: number;
  /** Scroll growth rate relative to hero progress (higher = faster). */
  scrollGrowSpeed: number;
};

/** Max scale added to side bills at full scroll (e.g. 0.18 = +18%). */
export const SIDE_SCROLL_GROW_MAX = 0.18;

/**
 * Bills positioned symmetrically from page center (50%).
 * Right side is generated by mirroring offset — same size, drop, and sway.
 */
const HOOK_DEFS: HookDef[] = [
  {
    offsetVw: 34,
    drop: 6,
    topExtra: 4,
    zIndex: 2,
    swayDelay: 0,
    swayDuration: 4.8,
    swayAngle: 1.5,
    scrollGrowSpeed: 0.65,
  },
  {
    offsetVw: 26,
    drop: 28,
    topExtra: 14,
    zIndex: 4,
    swayDelay: 0.5,
    swayDuration: 5.2,
    swayAngle: 1.8,
    scrollGrowSpeed: 1.05,
  },
  {
    offsetVw: 18,
    drop: 12,
    topExtra: 22,
    zIndex: 3,
    swayDelay: 1,
    swayDuration: 4.5,
    swayAngle: 1.4,
    scrollGrowSpeed: 0.85,
  },
  {
    offsetVw: 10,
    drop: 36,
    topExtra: 8,
    zIndex: 6,
    swayDelay: 0.25,
    swayDuration: 5.6,
    swayAngle: 2,
    scrollGrowSpeed: 1.35,
  },
];

export const SIDE_BILL_SCALE = 0.27;

export function scaledBillSize(baseScale: number) {
  return baseScale * BILL_SIZE_MULTIPLIER;
}

export const CENTER_BILL_SIZE = scaledBillSize(SIDE_BILL_SCALE);

/** Center bill scroll growth — 1× at top, 2.5× after scrolling through hero (3× the prior 0.5 expansion). */
export const CENTER_SCROLL_SCALE_START = 1;
export const CENTER_SCROLL_SCALE_END = 2.5;

/**
 * The focal line the bill's vertical center locks onto, as a fraction of the
 * viewport height (measured top→bottom). While the bill is small it hangs from
 * the top with its center above this line; once scaling would push its center
 * past the line, the bill is translated up so the center stays pinned here while
 * it keeps growing. 0.5 = viewport middle.
 */
export const CENTER_FOCAL_TARGET_VH = 0.5;

/**
 * How far past the footer's top edge the sticky bill keeps following the viewport,
 * expressed as a fraction of the rendered (scaled) bill image height. Larger values
 * let the bill extend further down into the footer before it releases.
 */
export const CENTER_STICKY_EXTEND_FRACTION = 0.12;

function toSideHook(def: HookDef, id: string, sign: "-" | "+"): SideHookConfig {
  return {
    id,
    left: `calc(50% ${sign} ${def.offsetVw}vw)`,
    drop: def.drop,
    topExtra: def.topExtra,
    scale: SIDE_BILL_SCALE,
    zIndex: def.zIndex,
    swayDelay: def.swayDelay,
    swayDuration: def.swayDuration,
    swayAngle: def.swayAngle,
    scrollGrowSpeed: def.scrollGrowSpeed,
  };
}

/** Symmetrical gallery — 4 bills per side (8 total), mirrored from center. */
export const SIDE_HOOKS: SideHookConfig[] = [
  ...HOOK_DEFS.map((def, i) => toSideHook(def, `l${i + 1}`, "-")),
  ...HOOK_DEFS.map((def, i) => toSideHook(def, `r${i + 1}`, "+")),
];
